import { AppState } from './types';
import { getTodayStr } from './utils/helpers';

const today = getTodayStr();

export const DEFAULT_INITIAL_STATE: AppState = {
  config: {
    appName: 'Sổ Chủ Nhiệm Điện Tử',
    className: '8A3',
    schoolYear: '2024 - 2025',
    teacherName: 'Nguyễn Thị Thùy Trang',
    teacherPassword: '123',
    availableClasses: ['8A3', '9A5', '7A1', '6A2'],
    classAvatar: '',
  },
  students: [
    {
      id: '15052012',
      name: 'Nguyễn Hoàng Nam',
      dob: '2012-05-15',
      gender: 'Nam',
      position: 'Lớp trưởng',
      phone: '0912345601',
      parentName: 'Nguyễn Văn Hùng',
      parentPhone: '0988111221',
      address: 'Số 12 ngõ 45 phố Hoàng Hoa Thám, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 9.2,
        'Ngữ văn': 8.5,
        'Tiếng Anh': 9.0,
        'Khoa học tự nhiên': 8.8,
        'Lịch sử & Địa lý': 8.7,
        'Tin học': 9.5,
        'Giáo dục công dân': 9.0,
        'Công nghệ': 8.5,
      },
      notes: 'Học sinh gương mẫu, năng động, điều hành lớp rất tốt.',
    },
    {
      id: '20082012',
      name: 'Trần Thị Mai Anh',
      dob: '2012-08-20',
      gender: 'Nữ',
      position: 'Lớp phó học tập',
      phone: '0912345602',
      parentName: 'Trần Quang Hải',
      parentPhone: '0988111222',
      address: 'Phòng 402 Tòa nhà CT3 Cầu Giấy, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 9.8,
        'Ngữ văn': 9.0,
        'Tiếng Anh': 9.5,
        'Khoa học tự nhiên': 9.6,
        'Lịch sử & Địa lý': 9.0,
        'Tin học': 9.0,
        'Giáo dục công dân': 9.5,
        'Công nghệ': 9.0,
      },
      notes: 'Học lực xuất sắc, luôn nhiệt tình phụ đạo các bạn trong lớp.',
    },
    {
      id: '10112012',
      name: 'Lê Quốc Bảo',
      dob: '2012-11-10',
      gender: 'Nam',
      position: 'Bí thư Chi đội',
      phone: '0912345603',
      parentName: 'Lê Văn Thành',
      parentPhone: '0988111223',
      address: 'Số 88 đường Lạc Long Quân, Tây Hồ, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 8.0,
        'Ngữ văn': 8.5,
        'Tiếng Anh': 8.8,
        'Khoa học tự nhiên': 8.2,
        'Lịch sử & Địa lý': 8.5,
        'Tin học': 8.5,
        'Giáo dục công dân': 9.0,
        'Công nghệ': 8.0,
      },
      notes: 'Tích cực tham gia phong trào Đội, giọng nói lưu loát, hoạt bát.',
    },
    {
      id: '03022012',
      name: 'Phạm Hương Giang',
      dob: '2012-02-03',
      gender: 'Nữ',
      position: 'Tổ trưởng Tổ 1',
      phone: '0912345604',
      parentName: 'Phạm Quốc Tuấn',
      parentPhone: '0988111224',
      address: 'Số 15 phố Kim Mã, Ba Đình, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 8.5,
        'Ngữ văn': 8.8,
        'Tiếng Anh': 8.5,
        'Khoa học tự nhiên': 8.0,
        'Lịch sử & Địa lý': 8.2,
        'Tin học': 8.5,
        'Giáo dục công dân': 9.0,
        'Công nghệ': 8.5,
      },
      notes: 'Tổ trưởng trách nhiệm, đôn đốc các bạn làm bài tập đầy đủ.',
    },
    {
      id: '18092012',
      name: 'Vũ Đình Khôi',
      dob: '2012-09-18',
      gender: 'Nam',
      position: 'Tổ trưởng Tổ 2',
      phone: '0912345605',
      parentName: 'Vũ Đức Minh',
      parentPhone: '0988111225',
      address: 'Số 32 ngõ 178 Đội Cấn, Ba Đình, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 8.7,
        'Ngữ văn': 7.8,
        'Tiếng Anh': 8.2,
        'Khoa học tự nhiên': 8.5,
        'Lịch sử & Địa lý': 7.9,
        'Tin học': 9.0,
        'Giáo dục công dân': 8.5,
        'Công nghệ': 8.0,
      },
      notes: 'Tư duy toán học và công nghệ tốt, trầm tính nhưng rất chu đáo.',
    },
    {
      id: '25122012',
      name: 'Đỗ Ngọc Linh',
      dob: '2012-12-25',
      gender: 'Nữ',
      position: 'Lớp phó Văn-Thể-Mỹ',
      phone: '0912345606',
      parentName: 'Đỗ Đình Trọng',
      parentPhone: '0988111226',
      address: 'Số 68 Thụy Khuê, Tây Hồ, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 8.0,
        'Ngữ văn': 9.2,
        'Tiếng Anh': 8.8,
        'Khoa học tự nhiên': 7.8,
        'Lịch sử & Địa lý': 8.5,
        'Tin học': 8.0,
        'Giáo dục công dân': 9.0,
        'Công nghệ': 8.5,
      },
      notes: 'Tài năng múa hát, vẽ bích báo rất đẹp, năng nổ trong các sự kiện.',
    },
    {
      id: '09042012',
      name: 'Hoàng Gia Huy',
      dob: '2012-04-09',
      gender: 'Nam',
      position: 'Tổ trưởng Tổ 3',
      phone: '0912345607',
      parentName: 'Hoàng Văn Sơn',
      parentPhone: '0988111227',
      address: 'Số 20 ngách 5 Nguyễn Khánh Toàn, Cầu Giấy, Hà Nội',
      password: '123',
      conduct: 'Khá',
      grades: {
        'Toán': 7.5,
        'Ngữ văn': 7.0,
        'Tiếng Anh': 7.8,
        'Khoa học tự nhiên': 7.5,
        'Lịch sử & Địa lý': 7.2,
        'Tin học': 8.5,
        'Giáo dục công dân': 8.0,
        'Công nghệ': 7.5,
      },
      notes: 'Cần chú ý tập trung hơn trong giờ Vật Lý, có tinh thần thể thao.',
    },
    {
      id: '14072012',
      name: 'Bùi Thảo Nguyên',
      dob: '2012-07-14',
      gender: 'Nữ',
      position: 'Tổ trưởng Tổ 4',
      phone: '0912345608',
      parentName: 'Bùi Tuấn Anh',
      parentPhone: '0988111228',
      address: 'Số 114 phố Nghĩa Tân, Cầu Giấy, Hà Nội',
      password: '123',
      conduct: 'Tốt',
      grades: {
        'Toán': 8.3,
        'Ngữ văn': 8.6,
        'Tiếng Anh': 8.5,
        'Khoa học tự nhiên': 8.1,
        'Lịch sử & Địa lý': 8.4,
        'Tin học': 8.2,
        'Giáo dục công dân': 9.0,
        'Công nghệ': 8.2,
      },
      notes: 'Chăm chỉ, ghi chép bài vở nề nếp, có tinh thần tương thân tương ái.',
    },
  ],
  attendance: [
    { id: 'att_01', studentId: '15052012', date: today, status: 'c' },
    { id: 'att_02', studentId: '20082012', date: today, status: 'c' },
    { id: 'att_03', studentId: '10112012', date: today, status: 'c' },
    { id: 'att_04', studentId: '03022012', date: today, status: 'c' },
    { id: 'att_05', studentId: '18092012', date: today, status: 'c' },
    { id: 'att_06', studentId: '25122012', date: today, status: 'm' },
    { id: 'att_07', studentId: '09042012', date: today, status: 'c' },
    { id: 'att_08', studentId: '14072012', date: today, status: 'c' },
  ],
  discipline: [
    {
      id: 'disc_01',
      studentId: '20082012',
      date: today,
      ruleName: 'Phát biểu xây dựng bài sôi nổi môn Toán',
      points: 5,
      note: 'Cô bộ môn tuyên dương giải bài nâng cao',
      type: 'plus',
    },
    {
      id: 'disc_02',
      studentId: '15052012',
      date: today,
      ruleName: 'Giữ gìn vệ sinh lớp học xuất sắc',
      points: 5,
      note: 'Nhắc nhở và chỉ huy trực nhật gọn gàng',
      type: 'plus',
    },
    {
      id: 'disc_03',
      studentId: '25122012',
      date: today,
      ruleName: 'Đi học muộn 10 phút',
      points: -2,
      note: 'Gặp sự cố xe đạp trên đường đến trường',
      type: 'minus',
    },
    {
      id: 'disc_04',
      studentId: '10112012',
      date: today,
      ruleName: 'Chuẩn bị chương trình sinh hoạt Đội chu đáo',
      points: 5,
      note: 'Được Đoàn trường khen ngợi',
      type: 'plus',
    },
  ],
  notes: [
    {
      id: 'note_01',
      studentId: '09042012',
      date: today,
      title: 'Nhắc nhở học tập',
      content: 'Nhắc nhở em Huy chuẩn bị bài tập môn KHTN đầy đủ trước khi lên lớp.',
      author: 'Cô Thùy Trang',
    },
    {
      id: 'note_02',
      studentId: '20082012',
      date: today,
      title: 'Tuyên dương học tập',
      content: 'Em Mai Anh hỗ trợ bạn Huy và Khôi ôn tập môn Toán giữa kỳ rất hiệu quả.',
      author: 'Cô Thùy Trang',
    },
  ],
  boardNotices: [
    {
      id: 'bn_01',
      title: 'Kế hoạch ôn tập và kiểm tra giữa học kỳ',
      content:
        'Các em học sinh lưu ý lịch kiểm tra giữa kỳ bắt đầu từ thứ Hai tuần tới. Đề nghị các tổ trưởng kiểm tra vở ghi chép và bài tập về nhà của các thành viên trước giờ sinh hoạt thứ 6.',
      date: today,
      priority: 'high',
      pinned: true,
      author: 'GVCN Cô Thùy Trang',
    },
    {
      id: 'bn_02',
      title: 'Phong trào Hoa Điểm 10 chào mừng Ngày Nhà Giáo Việt Nam 20/11',
      content:
        'Lớp phát động đợt thi đua cao điểm: mỗi điểm 9 hoặc 10 sẽ được cộng 5 bông hoa điểm tốt vào quỹ thi đua của tổ. Các em cố gắng phấn đấu!',
      date: today,
      priority: 'normal',
      pinned: true,
      author: 'GVCN Cô Thùy Trang',
    },
    {
      id: 'bn_03',
      title: 'Lịch trực nhật tuần này: Tổ 2',
      content:
        'Tổ 2 do bạn Vũ Đình Khôi phụ trách đảm nhận trực nhật lớp, lau bảng, đóng mở cửa sổ và kiểm tra quạt/đèn trước khi ra về.',
      date: today,
      priority: 'info',
      pinned: false,
      author: 'Ban Cán Sự Lớp',
    },
  ],
  seatingChart: {
    'desk_0_0': '15052012',
    'desk_0_1': '20082012',
    'desk_0_2': '10112012',
    'desk_0_3': '03022012',
    'desk_1_0': '18092012',
    'desk_1_1': '25122012',
    'desk_1_2': '09042012',
    'desk_1_3': '14072012',
  },
};
